services:
  directions-api-poc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      ORS_API_KEY: ${ORS_API_KEY}
    restart: unless-stopped
