services:
  directions-api-poc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_MAPTILER_API_KEY: ${VITE_MAPTILER_API_KEY}
    environment:
      NODE_ENV: production
      PORT: 3001
      ORS_API_KEY: ${ORS_API_KEY}
      VITE_MAPTILER_API_KEY: ${VITE_MAPTILER_API_KEY}
    restart: unless-stopped
